####################################################################################
####################################################################################
# STAGING DOCS SITE CONFIG
#
# Run with args:  --config config.toml,config.staging.toml
#
#  e.g. make HUGO_ARGS="--config config.toml,config.staging.toml" publish
#
####################################################################################
####################################################################################

#  Will override existing setting if present

baseURL = "https://docs-staging.corda.net/"
